# Generated by Django 4.0.4 on 2022-07-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author_token',
            new_name='auth_token',
        ),
    ]
